version: '3.8'
services:
  redis:
    image: redis:7.2-alpine
    container_name: universal-learning-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "no"]
    restart: unless-stopped
